<a href="https://colab.research.google.com/github/2303A52080/STML/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part-1 Implement Basic Data Structures using Numpy, Pandas**

In [ ]:
import numpy as np
import pandas as pd
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
print(type(list1),type(list2))

<class 'list'> <class 'list'>


In [ ]:
array1 = np.array(list1)
array2 = np.array(list2)
print(type(array1),type(array2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
mult = (array1*array2)
div = (array1/array2)
pow = (array1**2,array2**2)
add=(array1+array2)
print(mult)
print(div)
print(pow)
print(add)

[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
(array([ 1,  4,  9, 16, 25]), array([ 36,  49,  64,  81, 100]))
[ 7  9 11 13 15]


In [ ]:
sin_array = np.sin(array1)
log_array = np.log(array1)
log2_array = np.log2(array1)
exp_array = np.exp(array1)

print( sin_array)
print( log_array)
print( log2_array)
print( exp_array)


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
